sudo: false
language: java

jdk:
  - oraclejdk8

env:
  - TERM=dumb

cache:
  directories:
  - $HOME/.gradle

#before_install:
#  - rm -r ~/.gradle/caches

script:
  - ./gradlew --stacktrace
  - git clone https://github.com/huxi/lilith.git ~/builds/lilith
  - pushd ~/builds/lilith
  - git checkout $TRAVIS_BRANCH
  - ./gradlew --stacktrace install
  - popd

after_success:
  - ./gradlew --stacktrace cleanTest
  - ./gradlew --stacktrace jacocoRootReport
  - ./gradlew --stacktrace coveralls
